// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsexports = { 
    aws_project_region: 'us-east-1',
    region: 'us-east-1',
    identityPoolRegion: 'us-east-1',
    userPoolId: 'us-east-1_ZuzmLfCTT',
    userPoolWebClientId: '31moj5st11kjscavl62acv5t9o',
}

export default awsexports
